package org.densyakun.bukkit.dsp2.menumanager;
import java.util.UUID;

import org.bukkit.ChatColor;
import org.bukkit.Material;
import org.bukkit.event.inventory.InventoryClickEvent;
import org.bukkit.inventory.ItemStack;
import org.bukkit.inventory.meta.ItemMeta;
public class InventoryKeyboard extends MenuInventory {
	String str = new String();
	MenuKeyboardEnter enter;
	int type = 0;
	int mode = 0;
	public InventoryKeyboard(MenuManager menumanager, String name, UUID uuid, MenuKeyboardEnter enter, int type) {
		super(menumanager, 54, name, uuid);
		this.enter = enter;
		this.type = type;
		reload();
	}
	public void reload() {
		for (int a = 1; a < 54; a++) {
			getInventory().clear(a);
		}
		ItemStack item0 = new ItemStack(Material.GLASS);
		ItemMeta item0meta = item0.getItemMeta();
		if (mode == 0) {
			item0meta.setDisplayName(new StringBuffer(ChatColor.RED.toString()).append("0").toString());
			item0.setItemMeta(item0meta);
			getInventory().setItem(1, item0);
			item0meta.setDisplayName(new StringBuffer(ChatColor.RED.toString()).append("1").toString());
			item0.setItemMeta(item0meta);
			getInventory().setItem(2, item0);
			item0meta.setDisplayName(new StringBuffer(ChatColor.RED.toString()).append("2").toString());
			item0.setItemMeta(item0meta);
			getInventory().setItem(3, item0);
			item0meta.setDisplayName(new StringBuffer(ChatColor.RED.toString()).append("3").toString());
			item0.setItemMeta(item0meta);
			getInventory().setItem(4, item0);
			item0meta.setDisplayName(new StringBuffer(ChatColor.RED.toString()).append("4").toString());
			item0.setItemMeta(item0meta);
			getInventory().setItem(5, item0);
			item0meta.setDisplayName(new StringBuffer(ChatColor.RED.toString()).append("5").toString());
			item0.setItemMeta(item0meta);
			getInventory().setItem(6, item0);
			item0meta.setDisplayName(new StringBuffer(ChatColor.RED.toString()).append("6").toString());
			item0.setItemMeta(item0meta);
			getInventory().setItem(7, item0);
			item0meta.setDisplayName(new StringBuffer(ChatColor.RED.toString()).append("7").toString());
			item0.setItemMeta(item0meta);
			getInventory().setItem(8, item0);
			item0meta.setDisplayName(new StringBuffer(ChatColor.RED.toString()).append("8").toString());
			item0.setItemMeta(item0meta);
			getInventory().setItem(9, item0);
			item0meta.setDisplayName(new StringBuffer(ChatColor.RED.toString()).append("9").toString());
			item0.setItemMeta(item0meta);
			getInventory().setItem(10, item0);
		} else if (mode == 1) {
			item0meta.setDisplayName(new StringBuffer(ChatColor.RED.toString()).append("a").toString());
			item0.setItemMeta(item0meta);
			getInventory().setItem(11, item0);
			item0meta.setDisplayName(new StringBuffer(ChatColor.RED.toString()).append("b").toString());
			item0.setItemMeta(item0meta);
			getInventory().setItem(12, item0);
			item0meta.setDisplayName(new StringBuffer(ChatColor.RED.toString()).append("c").toString());
			item0.setItemMeta(item0meta);
			getInventory().setItem(13, item0);
			item0meta.setDisplayName(new StringBuffer(ChatColor.RED.toString()).append("d").toString());
			item0.setItemMeta(item0meta);
			getInventory().setItem(14, item0);
			item0meta.setDisplayName(new StringBuffer(ChatColor.RED.toString()).append("e").toString());
			item0.setItemMeta(item0meta);
			getInventory().setItem(15, item0);
			item0meta.setDisplayName(new StringBuffer(ChatColor.RED.toString()).append("f").toString());
			item0.setItemMeta(item0meta);
			getInventory().setItem(16, item0);
			item0meta.setDisplayName(new StringBuffer(ChatColor.RED.toString()).append("g").toString());
			item0.setItemMeta(item0meta);
			getInventory().setItem(17, item0);
			item0meta.setDisplayName(new StringBuffer(ChatColor.RED.toString()).append("h").toString());
			item0.setItemMeta(item0meta);
			getInventory().setItem(18, item0);
			item0meta.setDisplayName(new StringBuffer(ChatColor.RED.toString()).append("i").toString());
			item0.setItemMeta(item0meta);
			getInventory().setItem(19, item0);
			item0meta.setDisplayName(new StringBuffer(ChatColor.RED.toString()).append("j").toString());
			item0.setItemMeta(item0meta);
			getInventory().setItem(20, item0);
			item0meta.setDisplayName(new StringBuffer(ChatColor.RED.toString()).append("k").toString());
			item0.setItemMeta(item0meta);
			getInventory().setItem(21, item0);
			item0meta.setDisplayName(new StringBuffer(ChatColor.RED.toString()).append("l").toString());
			item0.setItemMeta(item0meta);
			getInventory().setItem(22, item0);
			item0meta.setDisplayName(new StringBuffer(ChatColor.RED.toString()).append("m").toString());
			item0.setItemMeta(item0meta);
			getInventory().setItem(23, item0);
			item0meta.setDisplayName(new StringBuffer(ChatColor.RED.toString()).append("n").toString());
			item0.setItemMeta(item0meta);
			getInventory().setItem(24, item0);
			item0meta.setDisplayName(new StringBuffer(ChatColor.RED.toString()).append("o").toString());
			item0.setItemMeta(item0meta);
			getInventory().setItem(25, item0);
			item0meta.setDisplayName(new StringBuffer(ChatColor.RED.toString()).append("p").toString());
			item0.setItemMeta(item0meta);
			getInventory().setItem(26, item0);
			item0meta.setDisplayName(new StringBuffer(ChatColor.RED.toString()).append("q").toString());
			item0.setItemMeta(item0meta);
			getInventory().setItem(27, item0);
			item0meta.setDisplayName(new StringBuffer(ChatColor.RED.toString()).append("r").toString());
			item0.setItemMeta(item0meta);
			getInventory().setItem(28, item0);
			item0meta.setDisplayName(new StringBuffer(ChatColor.RED.toString()).append("s").toString());
			item0.setItemMeta(item0meta);
			getInventory().setItem(29, item0);
			item0meta.setDisplayName(new StringBuffer(ChatColor.RED.toString()).append("t").toString());
			item0.setItemMeta(item0meta);
			getInventory().setItem(30, item0);
			item0meta.setDisplayName(new StringBuffer(ChatColor.RED.toString()).append("u").toString());
			item0.setItemMeta(item0meta);
			getInventory().setItem(31, item0);
			item0meta.setDisplayName(new StringBuffer(ChatColor.RED.toString()).append("v").toString());
			item0.setItemMeta(item0meta);
			getInventory().setItem(32, item0);
			item0meta.setDisplayName(new StringBuffer(ChatColor.RED.toString()).append("w").toString());
			item0.setItemMeta(item0meta);
			getInventory().setItem(33, item0);
			item0meta.setDisplayName(new StringBuffer(ChatColor.RED.toString()).append("x").toString());
			item0.setItemMeta(item0meta);
			getInventory().setItem(34, item0);
			item0meta.setDisplayName(new StringBuffer(ChatColor.RED.toString()).append("y").toString());
			item0.setItemMeta(item0meta);
			getInventory().setItem(35, item0);
			item0meta.setDisplayName(new StringBuffer(ChatColor.RED.toString()).append("z").toString());
			item0.setItemMeta(item0meta);
			getInventory().setItem(36, item0);
		} else if (mode == 2) {
			item0meta.setDisplayName(new StringBuffer(ChatColor.RED.toString()).append("あ").toString());
			item0.setItemMeta(item0meta);
			getInventory().setItem(1, item0);
			item0meta.setDisplayName(new StringBuffer(ChatColor.RED.toString()).append("い").toString());
			item0.setItemMeta(item0meta);
			getInventory().setItem(2, item0);
			item0meta.setDisplayName(new StringBuffer(ChatColor.RED.toString()).append("う").toString());
			item0.setItemMeta(item0meta);
			getInventory().setItem(3, item0);
			item0meta.setDisplayName(new StringBuffer(ChatColor.RED.toString()).append("え").toString());
			item0.setItemMeta(item0meta);
			getInventory().setItem(4, item0);
			item0meta.setDisplayName(new StringBuffer(ChatColor.RED.toString()).append("お").toString());
			item0.setItemMeta(item0meta);
			getInventory().setItem(5, item0);
			item0meta.setDisplayName(new StringBuffer(ChatColor.RED.toString()).append("か").toString());
			item0.setItemMeta(item0meta);
			getInventory().setItem(6, item0);
			item0meta.setDisplayName(new StringBuffer(ChatColor.RED.toString()).append("き").toString());
			item0.setItemMeta(item0meta);
			getInventory().setItem(7, item0);
			item0meta.setDisplayName(new StringBuffer(ChatColor.RED.toString()).append("く").toString());
			item0.setItemMeta(item0meta);
			getInventory().setItem(8, item0);
			item0meta.setDisplayName(new StringBuffer(ChatColor.RED.toString()).append("け").toString());
			item0.setItemMeta(item0meta);
			getInventory().setItem(9, item0);
			item0meta.setDisplayName(new StringBuffer(ChatColor.RED.toString()).append("こ").toString());
			item0.setItemMeta(item0meta);
			getInventory().setItem(10, item0);
			item0meta.setDisplayName(new StringBuffer(ChatColor.RED.toString()).append("さ").toString());
			item0.setItemMeta(item0meta);
			getInventory().setItem(11, item0);
			item0meta.setDisplayName(new StringBuffer(ChatColor.RED.toString()).append("し").toString());
			item0.setItemMeta(item0meta);
			getInventory().setItem(12, item0);
			item0meta.setDisplayName(new StringBuffer(ChatColor.RED.toString()).append("す").toString());
			item0.setItemMeta(item0meta);
			getInventory().setItem(13, item0);
			item0meta.setDisplayName(new StringBuffer(ChatColor.RED.toString()).append("せ").toString());
			item0.setItemMeta(item0meta);
			getInventory().setItem(14, item0);
			item0meta.setDisplayName(new StringBuffer(ChatColor.RED.toString()).append("そ").toString());
			item0.setItemMeta(item0meta);
			getInventory().setItem(15, item0);
			item0meta.setDisplayName(new StringBuffer(ChatColor.RED.toString()).append("た").toString());
			item0.setItemMeta(item0meta);
			getInventory().setItem(16, item0);
			item0meta.setDisplayName(new StringBuffer(ChatColor.RED.toString()).append("ち").toString());
			item0.setItemMeta(item0meta);
			getInventory().setItem(17, item0);
			item0meta.setDisplayName(new StringBuffer(ChatColor.RED.toString()).append("つ").toString());
			item0.setItemMeta(item0meta);
			getInventory().setItem(18, item0);
			item0meta.setDisplayName(new StringBuffer(ChatColor.RED.toString()).append("て").toString());
			item0.setItemMeta(item0meta);
			getInventory().setItem(19, item0);
			item0meta.setDisplayName(new StringBuffer(ChatColor.RED.toString()).append("と").toString());
			item0.setItemMeta(item0meta);
			getInventory().setItem(20, item0);
			item0meta.setDisplayName(new StringBuffer(ChatColor.RED.toString()).append("な").toString());
			item0.setItemMeta(item0meta);
			getInventory().setItem(21, item0);
			item0meta.setDisplayName(new StringBuffer(ChatColor.RED.toString()).append("に").toString());
			item0.setItemMeta(item0meta);
			getInventory().setItem(22, item0);
			item0meta.setDisplayName(new StringBuffer(ChatColor.RED.toString()).append("ぬ").toString());
			item0.setItemMeta(item0meta);
			getInventory().setItem(23, item0);
			item0meta.setDisplayName(new StringBuffer(ChatColor.RED.toString()).append("ね").toString());
			item0.setItemMeta(item0meta);
			getInventory().setItem(24, item0);
			item0meta.setDisplayName(new StringBuffer(ChatColor.RED.toString()).append("の").toString());
			item0.setItemMeta(item0meta);
			getInventory().setItem(25, item0);
			item0meta.setDisplayName(new StringBuffer(ChatColor.RED.toString()).append("は").toString());
			item0.setItemMeta(item0meta);
			getInventory().setItem(26, item0);
			item0meta.setDisplayName(new StringBuffer(ChatColor.RED.toString()).append("ひ").toString());
			item0.setItemMeta(item0meta);
			getInventory().setItem(27, item0);
			item0meta.setDisplayName(new StringBuffer(ChatColor.RED.toString()).append("ふ").toString());
			item0.setItemMeta(item0meta);
			getInventory().setItem(28, item0);
			item0meta.setDisplayName(new StringBuffer(ChatColor.RED.toString()).append("へ").toString());
			item0.setItemMeta(item0meta);
			getInventory().setItem(29, item0);
			item0meta.setDisplayName(new StringBuffer(ChatColor.RED.toString()).append("ほ").toString());
			item0.setItemMeta(item0meta);
			getInventory().setItem(30, item0);
			item0meta.setDisplayName(new StringBuffer(ChatColor.RED.toString()).append("ま").toString());
			item0.setItemMeta(item0meta);
			getInventory().setItem(31, item0);
			item0meta.setDisplayName(new StringBuffer(ChatColor.RED.toString()).append("み").toString());
			item0.setItemMeta(item0meta);
			getInventory().setItem(32, item0);
			item0meta.setDisplayName(new StringBuffer(ChatColor.RED.toString()).append("む").toString());
			item0.setItemMeta(item0meta);
			getInventory().setItem(33, item0);
			item0meta.setDisplayName(new StringBuffer(ChatColor.RED.toString()).append("め").toString());
			item0.setItemMeta(item0meta);
			getInventory().setItem(34, item0);
			item0meta.setDisplayName(new StringBuffer(ChatColor.RED.toString()).append("も").toString());
			item0.setItemMeta(item0meta);
			getInventory().setItem(35, item0);
			item0meta.setDisplayName(new StringBuffer(ChatColor.RED.toString()).append("や").toString());
			item0.setItemMeta(item0meta);
			getInventory().setItem(36, item0);
			item0meta.setDisplayName(new StringBuffer(ChatColor.RED.toString()).append("ゆ").toString());
			item0.setItemMeta(item0meta);
			getInventory().setItem(37, item0);
			item0meta.setDisplayName(new StringBuffer(ChatColor.RED.toString()).append("よ").toString());
			item0.setItemMeta(item0meta);
			getInventory().setItem(38, item0);
			item0meta.setDisplayName(new StringBuffer(ChatColor.RED.toString()).append("ら").toString());
			item0.setItemMeta(item0meta);
			getInventory().setItem(39, item0);
			item0meta.setDisplayName(new StringBuffer(ChatColor.RED.toString()).append("り").toString());
			item0.setItemMeta(item0meta);
			getInventory().setItem(40, item0);
			item0meta.setDisplayName(new StringBuffer(ChatColor.RED.toString()).append("る").toString());
			item0.setItemMeta(item0meta);
			getInventory().setItem(41, item0);
			item0meta.setDisplayName(new StringBuffer(ChatColor.RED.toString()).append("れ").toString());
			item0.setItemMeta(item0meta);
			getInventory().setItem(42, item0);
			item0meta.setDisplayName(new StringBuffer(ChatColor.RED.toString()).append("ろ").toString());
			item0.setItemMeta(item0meta);
			getInventory().setItem(43, item0);
			item0meta.setDisplayName(new StringBuffer(ChatColor.RED.toString()).append("わ").toString());
			item0.setItemMeta(item0meta);
			getInventory().setItem(44, item0);
			item0meta.setDisplayName(new StringBuffer(ChatColor.RED.toString()).append("を").toString());
			item0.setItemMeta(item0meta);
			getInventory().setItem(45, item0);
			item0meta.setDisplayName(new StringBuffer(ChatColor.RED.toString()).append("ん").toString());
			item0.setItemMeta(item0meta);
			getInventory().setItem(46, item0);
			item0meta.setDisplayName(new StringBuffer(ChatColor.RED.toString()).append("ー").toString());
			item0.setItemMeta(item0meta);
			getInventory().setItem(47, item0);
		} else if (mode == 3) {
			item0meta.setDisplayName(new StringBuffer(ChatColor.RED.toString()).append("ア").toString());
			item0.setItemMeta(item0meta);
			getInventory().setItem(1, item0);
			item0meta.setDisplayName(new StringBuffer(ChatColor.RED.toString()).append("イ").toString());
			item0.setItemMeta(item0meta);
			getInventory().setItem(2, item0);
			item0meta.setDisplayName(new StringBuffer(ChatColor.RED.toString()).append("ウ").toString());
			item0.setItemMeta(item0meta);
			getInventory().setItem(3, item0);
			item0meta.setDisplayName(new StringBuffer(ChatColor.RED.toString()).append("エ").toString());
			item0.setItemMeta(item0meta);
			getInventory().setItem(4, item0);
			item0meta.setDisplayName(new StringBuffer(ChatColor.RED.toString()).append("オ").toString());
			item0.setItemMeta(item0meta);
			getInventory().setItem(5, item0);
			item0meta.setDisplayName(new StringBuffer(ChatColor.RED.toString()).append("カ").toString());
			item0.setItemMeta(item0meta);
			getInventory().setItem(6, item0);
			item0meta.setDisplayName(new StringBuffer(ChatColor.RED.toString()).append("キ").toString());
			item0.setItemMeta(item0meta);
			getInventory().setItem(7, item0);
			item0meta.setDisplayName(new StringBuffer(ChatColor.RED.toString()).append("ク").toString());
			item0.setItemMeta(item0meta);
			getInventory().setItem(8, item0);
			item0meta.setDisplayName(new StringBuffer(ChatColor.RED.toString()).append("ケ").toString());
			item0.setItemMeta(item0meta);
			getInventory().setItem(9, item0);
			item0meta.setDisplayName(new StringBuffer(ChatColor.RED.toString()).append("コ").toString());
			item0.setItemMeta(item0meta);
			getInventory().setItem(10, item0);
			item0meta.setDisplayName(new StringBuffer(ChatColor.RED.toString()).append("サ").toString());
			item0.setItemMeta(item0meta);
			getInventory().setItem(11, item0);
			item0meta.setDisplayName(new StringBuffer(ChatColor.RED.toString()).append("シ").toString());
			item0.setItemMeta(item0meta);
			getInventory().setItem(12, item0);
			item0meta.setDisplayName(new StringBuffer(ChatColor.RED.toString()).append("ス").toString());
			item0.setItemMeta(item0meta);
			getInventory().setItem(13, item0);
			item0meta.setDisplayName(new StringBuffer(ChatColor.RED.toString()).append("セ").toString());
			item0.setItemMeta(item0meta);
			getInventory().setItem(14, item0);
			item0meta.setDisplayName(new StringBuffer(ChatColor.RED.toString()).append("ソ").toString());
			item0.setItemMeta(item0meta);
			getInventory().setItem(15, item0);
			item0meta.setDisplayName(new StringBuffer(ChatColor.RED.toString()).append("タ").toString());
			item0.setItemMeta(item0meta);
			getInventory().setItem(16, item0);
			item0meta.setDisplayName(new StringBuffer(ChatColor.RED.toString()).append("チ").toString());
			item0.setItemMeta(item0meta);
			getInventory().setItem(17, item0);
			item0meta.setDisplayName(new StringBuffer(ChatColor.RED.toString()).append("ツ").toString());
			item0.setItemMeta(item0meta);
			getInventory().setItem(18, item0);
			item0meta.setDisplayName(new StringBuffer(ChatColor.RED.toString()).append("テ").toString());
			item0.setItemMeta(item0meta);
			getInventory().setItem(19, item0);
			item0meta.setDisplayName(new StringBuffer(ChatColor.RED.toString()).append("ト").toString());
			item0.setItemMeta(item0meta);
			getInventory().setItem(20, item0);
			item0meta.setDisplayName(new StringBuffer(ChatColor.RED.toString()).append("ナ").toString());
			item0.setItemMeta(item0meta);
			getInventory().setItem(21, item0);
			item0meta.setDisplayName(new StringBuffer(ChatColor.RED.toString()).append("ニ").toString());
			item0.setItemMeta(item0meta);
			getInventory().setItem(22, item0);
			item0meta.setDisplayName(new StringBuffer(ChatColor.RED.toString()).append("ヌ").toString());
			item0.setItemMeta(item0meta);
			getInventory().setItem(23, item0);
			item0meta.setDisplayName(new StringBuffer(ChatColor.RED.toString()).append("ネ").toString());
			item0.setItemMeta(item0meta);
			getInventory().setItem(24, item0);
			item0meta.setDisplayName(new StringBuffer(ChatColor.RED.toString()).append("ノ").toString());
			item0.setItemMeta(item0meta);
			getInventory().setItem(25, item0);
			item0meta.setDisplayName(new StringBuffer(ChatColor.RED.toString()).append("ハ").toString());
			item0.setItemMeta(item0meta);
			getInventory().setItem(26, item0);
			item0meta.setDisplayName(new StringBuffer(ChatColor.RED.toString()).append("ヒ").toString());
			item0.setItemMeta(item0meta);
			getInventory().setItem(27, item0);
			item0meta.setDisplayName(new StringBuffer(ChatColor.RED.toString()).append("フ").toString());
			item0.setItemMeta(item0meta);
			getInventory().setItem(28, item0);
			item0meta.setDisplayName(new StringBuffer(ChatColor.RED.toString()).append("ヘ").toString());
			item0.setItemMeta(item0meta);
			getInventory().setItem(29, item0);
			item0meta.setDisplayName(new StringBuffer(ChatColor.RED.toString()).append("ホ").toString());
			item0.setItemMeta(item0meta);
			getInventory().setItem(30, item0);
			item0meta.setDisplayName(new StringBuffer(ChatColor.RED.toString()).append("マ").toString());
			item0.setItemMeta(item0meta);
			getInventory().setItem(31, item0);
			item0meta.setDisplayName(new StringBuffer(ChatColor.RED.toString()).append("ミ").toString());
			item0.setItemMeta(item0meta);
			getInventory().setItem(32, item0);
			item0meta.setDisplayName(new StringBuffer(ChatColor.RED.toString()).append("ム").toString());
			item0.setItemMeta(item0meta);
			getInventory().setItem(33, item0);
			item0meta.setDisplayName(new StringBuffer(ChatColor.RED.toString()).append("メ").toString());
			item0.setItemMeta(item0meta);
			getInventory().setItem(34, item0);
			item0meta.setDisplayName(new StringBuffer(ChatColor.RED.toString()).append("モ").toString());
			item0.setItemMeta(item0meta);
			getInventory().setItem(35, item0);
			item0meta.setDisplayName(new StringBuffer(ChatColor.RED.toString()).append("ヤ").toString());
			item0.setItemMeta(item0meta);
			getInventory().setItem(36, item0);
			item0meta.setDisplayName(new StringBuffer(ChatColor.RED.toString()).append("ユ").toString());
			item0.setItemMeta(item0meta);
			getInventory().setItem(37, item0);
			item0meta.setDisplayName(new StringBuffer(ChatColor.RED.toString()).append("ヨ").toString());
			item0.setItemMeta(item0meta);
			getInventory().setItem(38, item0);
			item0meta.setDisplayName(new StringBuffer(ChatColor.RED.toString()).append("ラ").toString());
			item0.setItemMeta(item0meta);
			getInventory().setItem(39, item0);
			item0meta.setDisplayName(new StringBuffer(ChatColor.RED.toString()).append("リ").toString());
			item0.setItemMeta(item0meta);
			getInventory().setItem(40, item0);
			item0meta.setDisplayName(new StringBuffer(ChatColor.RED.toString()).append("ル").toString());
			item0.setItemMeta(item0meta);
			getInventory().setItem(41, item0);
			item0meta.setDisplayName(new StringBuffer(ChatColor.RED.toString()).append("レ").toString());
			item0.setItemMeta(item0meta);
			getInventory().setItem(42, item0);
			item0meta.setDisplayName(new StringBuffer(ChatColor.RED.toString()).append("ロ").toString());
			item0.setItemMeta(item0meta);
			getInventory().setItem(43, item0);
			item0meta.setDisplayName(new StringBuffer(ChatColor.RED.toString()).append("ワ").toString());
			item0.setItemMeta(item0meta);
			getInventory().setItem(44, item0);
			item0meta.setDisplayName(new StringBuffer(ChatColor.RED.toString()).append("ヲ").toString());
			item0.setItemMeta(item0meta);
			getInventory().setItem(45, item0);
			item0meta.setDisplayName(new StringBuffer(ChatColor.RED.toString()).append("ン").toString());
			item0.setItemMeta(item0meta);
			getInventory().setItem(46, item0);
			item0meta.setDisplayName(new StringBuffer(ChatColor.RED.toString()).append("ー").toString());
			item0.setItemMeta(item0meta);
			getInventory().setItem(47, item0);
		} else if (mode == 4) {
			item0meta.setDisplayName(new StringBuffer(ChatColor.RED.toString()).append("銀").toString());
			item0.setItemMeta(item0meta);
			getInventory().setItem(1, item0);
			item0meta.setDisplayName(new StringBuffer(ChatColor.RED.toString()).append("行").toString());
			item0.setItemMeta(item0meta);
			getInventory().setItem(2, item0);
		} else if (mode == 5) {
			item0meta.setDisplayName(new StringBuffer(ChatColor.RED.toString()).append("が").toString());
			item0.setItemMeta(item0meta);
			getInventory().setItem(1, item0);
			item0meta.setDisplayName(new StringBuffer(ChatColor.RED.toString()).append("ぎ").toString());
			item0.setItemMeta(item0meta);
			getInventory().setItem(2, item0);
			item0meta.setDisplayName(new StringBuffer(ChatColor.RED.toString()).append("ぐ").toString());
			item0.setItemMeta(item0meta);
			getInventory().setItem(3, item0);
			item0meta.setDisplayName(new StringBuffer(ChatColor.RED.toString()).append("げ").toString());
			item0.setItemMeta(item0meta);
			getInventory().setItem(4, item0);
			item0meta.setDisplayName(new StringBuffer(ChatColor.RED.toString()).append("ご").toString());
			item0.setItemMeta(item0meta);
			getInventory().setItem(5, item0);
			item0meta.setDisplayName(new StringBuffer(ChatColor.RED.toString()).append("ざ").toString());
			item0.setItemMeta(item0meta);
			getInventory().setItem(6, item0);
			item0meta.setDisplayName(new StringBuffer(ChatColor.RED.toString()).append("じ").toString());
			item0.setItemMeta(item0meta);
			getInventory().setItem(7, item0);
			item0meta.setDisplayName(new StringBuffer(ChatColor.RED.toString()).append("ず").toString());
			item0.setItemMeta(item0meta);
			getInventory().setItem(8, item0);
			item0meta.setDisplayName(new StringBuffer(ChatColor.RED.toString()).append("ぜ").toString());
			item0.setItemMeta(item0meta);
			getInventory().setItem(9, item0);
			item0meta.setDisplayName(new StringBuffer(ChatColor.RED.toString()).append("ぞ").toString());
			item0.setItemMeta(item0meta);
			getInventory().setItem(10, item0);
			item0meta.setDisplayName(new StringBuffer(ChatColor.RED.toString()).append("だ").toString());
			item0.setItemMeta(item0meta);
			getInventory().setItem(11, item0);
			item0meta.setDisplayName(new StringBuffer(ChatColor.RED.toString()).append("ぢ").toString());
			item0.setItemMeta(item0meta);
			getInventory().setItem(12, item0);
			item0meta.setDisplayName(new StringBuffer(ChatColor.RED.toString()).append("づ").toString());
			item0.setItemMeta(item0meta);
			getInventory().setItem(13, item0);
			item0meta.setDisplayName(new StringBuffer(ChatColor.RED.toString()).append("で").toString());
			item0.setItemMeta(item0meta);
			getInventory().setItem(14, item0);
			item0meta.setDisplayName(new StringBuffer(ChatColor.RED.toString()).append("ど").toString());
			item0.setItemMeta(item0meta);
			getInventory().setItem(15, item0);
			item0meta.setDisplayName(new StringBuffer(ChatColor.RED.toString()).append("ば").toString());
			item0.setItemMeta(item0meta);
			getInventory().setItem(16, item0);
			item0meta.setDisplayName(new StringBuffer(ChatColor.RED.toString()).append("び").toString());
			item0.setItemMeta(item0meta);
			getInventory().setItem(17, item0);
			item0meta.setDisplayName(new StringBuffer(ChatColor.RED.toString()).append("ぶ").toString());
			item0.setItemMeta(item0meta);
			getInventory().setItem(18, item0);
			item0meta.setDisplayName(new StringBuffer(ChatColor.RED.toString()).append("べ").toString());
			item0.setItemMeta(item0meta);
			getInventory().setItem(19, item0);
			item0meta.setDisplayName(new StringBuffer(ChatColor.RED.toString()).append("ぼ").toString());
			item0.setItemMeta(item0meta);
			getInventory().setItem(20, item0);
		} else if (mode == 6) {
			item0meta.setDisplayName(new StringBuffer(ChatColor.RED.toString()).append("ガ").toString());
			item0.setItemMeta(item0meta);
			getInventory().setItem(1, item0);
			item0meta.setDisplayName(new StringBuffer(ChatColor.RED.toString()).append("ギ").toString());
			item0.setItemMeta(item0meta);
			getInventory().setItem(2, item0);
			item0meta.setDisplayName(new StringBuffer(ChatColor.RED.toString()).append("グ").toString());
			item0.setItemMeta(item0meta);
			getInventory().setItem(3, item0);
			item0meta.setDisplayName(new StringBuffer(ChatColor.RED.toString()).append("ゲ").toString());
			item0.setItemMeta(item0meta);
			getInventory().setItem(4, item0);
			item0meta.setDisplayName(new StringBuffer(ChatColor.RED.toString()).append("ゴ").toString());
			item0.setItemMeta(item0meta);
			getInventory().setItem(5, item0);
			item0meta.setDisplayName(new StringBuffer(ChatColor.RED.toString()).append("ザ").toString());
			item0.setItemMeta(item0meta);
			getInventory().setItem(6, item0);
			item0meta.setDisplayName(new StringBuffer(ChatColor.RED.toString()).append("ジ").toString());
			item0.setItemMeta(item0meta);
			getInventory().setItem(7, item0);
			item0meta.setDisplayName(new StringBuffer(ChatColor.RED.toString()).append("ズ").toString());
			item0.setItemMeta(item0meta);
			getInventory().setItem(8, item0);
			item0meta.setDisplayName(new StringBuffer(ChatColor.RED.toString()).append("ゼ").toString());
			item0.setItemMeta(item0meta);
			getInventory().setItem(9, item0);
			item0meta.setDisplayName(new StringBuffer(ChatColor.RED.toString()).append("ゾ").toString());
			item0.setItemMeta(item0meta);
			getInventory().setItem(10, item0);
			item0meta.setDisplayName(new StringBuffer(ChatColor.RED.toString()).append("ダ").toString());
			item0.setItemMeta(item0meta);
			getInventory().setItem(11, item0);
			item0meta.setDisplayName(new StringBuffer(ChatColor.RED.toString()).append("ヂ").toString());
			item0.setItemMeta(item0meta);
			getInventory().setItem(12, item0);
			item0meta.setDisplayName(new StringBuffer(ChatColor.RED.toString()).append("ヅ").toString());
			item0.setItemMeta(item0meta);
			getInventory().setItem(13, item0);
			item0meta.setDisplayName(new StringBuffer(ChatColor.RED.toString()).append("デ").toString());
			item0.setItemMeta(item0meta);
			getInventory().setItem(14, item0);
			item0meta.setDisplayName(new StringBuffer(ChatColor.RED.toString()).append("ド").toString());
			item0.setItemMeta(item0meta);
			getInventory().setItem(15, item0);
			item0meta.setDisplayName(new StringBuffer(ChatColor.RED.toString()).append("バ").toString());
			item0.setItemMeta(item0meta);
			getInventory().setItem(16, item0);
			item0meta.setDisplayName(new StringBuffer(ChatColor.RED.toString()).append("ビ").toString());
			item0.setItemMeta(item0meta);
			getInventory().setItem(17, item0);
			item0meta.setDisplayName(new StringBuffer(ChatColor.RED.toString()).append("ブ").toString());
			item0.setItemMeta(item0meta);
			getInventory().setItem(18, item0);
			item0meta.setDisplayName(new StringBuffer(ChatColor.RED.toString()).append("ベ").toString());
			item0.setItemMeta(item0meta);
			getInventory().setItem(19, item0);
			item0meta.setDisplayName(new StringBuffer(ChatColor.RED.toString()).append("ボ").toString());
			item0.setItemMeta(item0meta);
			getInventory().setItem(20, item0);
		}
		item0meta.setDisplayName(new StringBuffer(ChatColor.RED.toString()).append("決定").toString());
		item0.setItemMeta(item0meta);
		getInventory().setItem(48, item0);
		if (type != 0) {
			item0meta.setDisplayName(new StringBuffer(ChatColor.RED.toString()).append("切り替え").toString());
			item0.setItemMeta(item0meta);
			getInventory().setItem(49, item0);
		}
		item0meta.setDisplayName(new StringBuffer(ChatColor.RED.toString()).append(str).toString());
		item0.setItemMeta(item0meta);
		item0meta = null;
		getInventory().setItem(50, item0);
		item0 = null;
	}
	@Override
	public void Click(InventoryClickEvent e) {
		switch (e.getRawSlot()) {
		case 48:
			if (0 < str.length()) {
				if (type == 0) {
					enter.Enter(Integer.valueOf(str));
				} else {
					enter.Enter(str);
				}
			}
			break;
		case 49:
			if (type == 2) {
				if (mode == 0) {
					mode = 1;
				} else if (mode == 1) {
					mode = 2;
				} else if (mode == 2) {
					mode = 3;
				} else if (mode == 3) {
					mode = 4;
				} else if (mode == 4) {
					mode = 5;
				} else if (mode == 5) {
					mode = 6;
				} else {
					mode = 0;
				}
				reload();
			} else if (type == 1) {
				if (mode == 0) {
					mode = 1;
				} else {
					mode = 0;
				}
				reload();
			}
			break;
		default:
			if (e.getInventory().getItem(e.getRawSlot()) != null) {
				str += ChatColor.stripColor(e.getInventory().getItem(e.getRawSlot()).getItemMeta().getDisplayName());
				reload();
			}
			break;
		}
	}
}
