name: DSP2
main: org.densyakun.bukkit.dsp2.Main
version: 1.016-beta
author: Densyakun
website: http://densyakuncreate.wiki.fc2.com/
softdepend: [HubSpawn, iConomy]
commands:
   dsp:
   menu:
   nick:
